### ISSUE TITLE
Black screen after load

### ISSUE THREAD

**Issue by awsumbill** [fuzzbuzzbay999/hosted-websites#1]
https://user-images.githubusercontent.com/47586568/187540669-9c8b459a-efef-444a-a8f5-aa0ce2d96bfc.mp4

**Comment by fuzzbuzzbay999** [comment]
ima be honest i didnt expect it to get that far, on a mobile browser

**Comment by fuzzbuzzbay999** [comment]
so i am useing ruffle
https://ruffle.rs/
to run flash(.swf) games
and it is currently in development of avm2 which that game is made in, so I cant really do much about it other than just wait

**Comment by awsumbill** [comment]
So would it work on a desktop browser?
